<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Quote;

class QuoteSeeder extends Seeder
{
    public function run(): void
    {
        $quotes = [
            'Success is not final, failure is not fatal: It is the courage to continue that counts. – Winston Churchill',
            'The only way to do great work is to love what you do. – Steve Jobs',
            'Believe you can and you’re halfway there. – Theodore Roosevelt',
            'Opportunities don’t happen, you create them. – Chris Grosser',
            'Don’t watch the clock; do what it does. Keep going. – Sam Levenson',
            'The future depends on what you do today. – Mahatma Gandhi',
            'Dream big and dare to fail. – Norman Vaughan',
            'Start where you are. Use what you have. Do what you can. – Arthur Ashe',
            'Your limitation—it’s only your imagination.',
            'Push yourself, because no one else is going to do it for you.',
            'Great things never come from comfort zones.',
            'Success doesn’t just find you. You have to go out and get it.',
            'The harder you work for something, the greater you’ll feel when you achieve it.',
            'Don’t stop when you’re tired. Stop when you’re done.',
            'Wake up with determination. Go to bed with satisfaction.',
            'Do something today that your future self will thank you for.',
            'Little things make big days.',
            'It’s going to be hard, but hard does not mean impossible.',
            'Don’t wait for opportunity. Create it.',
            'Sometimes we’re tested not to show our weaknesses, but to discover our strengths.',
            'The key to success is to focus on goals, not obstacles.',
            'Dream it. Wish it. Do it.',
            'Stay positive. Work hard. Make it happen.',
            'Doubt kills more dreams than failure ever will. – Suzy Kassem',
            'Act as if what you do makes a difference. It does. – William James',
            'Quality is not an act, it is a habit. – Aristotle',
            'With the new day comes new strength and new thoughts. – Eleanor Roosevelt',
            'The only limit to our realization of tomorrow will be our doubts of today. – Franklin D. Roosevelt',
            'It always seems impossible until it’s done. – Nelson Mandela',
            'You are never too old to set another goal or to dream a new dream. – C.S. Lewis',
            'If you can dream it, you can do it. – Walt Disney',
            'Keep your face always toward the sunshine—and shadows will fall behind you. – Walt Whitman',
            'What you get by achieving your goals is not as important as what you become by achieving your goals. – Zig Ziglar',
            'Perseverance is not a long race; it is many short races one after the other. – Walter Elliot',
            'The best way to get started is to quit talking and begin doing. – Walt Disney',
            'Don’t let yesterday take up too much of today. – Will Rogers',
            'You don’t have to be great to start, but you have to start to be great. – Zig Ziglar',
            'The only place where success comes before work is in the dictionary. – Vidal Sassoon',
            'Hardships often prepare ordinary people for an extraordinary destiny. – C.S. Lewis',
            'Success is walking from failure to failure with no loss of enthusiasm. – Winston Churchill',
            'The secret of getting ahead is getting started. – Mark Twain',
            'It does not matter how slowly you go as long as you do not stop. – Confucius',
            'Everything you’ve ever wanted is on the other side of fear. – George Addair',
            'Opportunities are usually disguised as hard work, so most people don’t recognize them. – Ann Landers',
            'Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart. – Roy T. Bennett',
            'If you want to achieve greatness stop asking for permission. – Anonymous',
            'Go the extra mile. It’s never crowded there. – Dr. Wayne D. Dyer',
            'You are braver than you believe, stronger than you seem, and smarter than you think. – A.A. Milne',
            'Difficult roads often lead to beautiful destinations.',
            'Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. – Christian D. Larson',
            'The only way to achieve the impossible is to believe it is possible. – Charles Kingsleigh',
            'Success is not how high you have climbed, but how you make a positive difference to the world. – Roy T. Bennett',
            'You miss 100% of the shots you don’t take. – Wayne Gretzky',
            'The journey of a thousand miles begins with one step. – Lao Tzu',
            'Don’t limit your challenges. Challenge your limits.',
            'Doubt whom you will, but never yourself. – Christian Nestell Bovee',
            'You are capable of amazing things.',
            'The best view comes after the hardest climb.',
            'If you’re going through hell, keep going. – Winston Churchill',
            'The difference between ordinary and extraordinary is that little extra.',
            'You don’t have to see the whole staircase, just take the first step. – Martin Luther King Jr.',
            'Strive not to be a success, but rather to be of value. – Albert Einstein',
            'Don’t be afraid to give up the good to go for the great. – John D. Rockefeller',
            'The harder the battle, the sweeter the victory.',
            'Success is the sum of small efforts, repeated day in and day out. – Robert Collier',
            'You can if you think you can. – George Reeves',
            'The only person you are destined to become is the person you decide to be. – Ralph Waldo Emerson',
            'Don’t count the days, make the days count. – Muhammad Ali',
            'If you want to lift yourself up, lift up someone else. – Booker T. Washington',
            'The mind is everything. What you think you become. – Buddha',
            'The best revenge is massive success. – Frank Sinatra',
            'Difficulties in life are intended to make us better, not bitter. – Dan Reeves',
            'You are the artist of your own life. Don’t hand the paintbrush to anyone else.',
            'If you want something you’ve never had, you must be willing to do something you’ve never done.',
            'Don’t quit. Suffer now and live the rest of your life as a champion. – Muhammad Ali',
            'The only thing standing between you and your goal is the story you keep telling yourself as to why you can’t achieve it. – Jordan Belfort',
            'You don’t need to see the whole path. Just take the first step.',
            'Success is not for the chosen few, but for the few who choose it.',
            'You are stronger than you think.',
            'The pain you feel today will be the strength you feel tomorrow.',
            'Don’t be afraid to start over. It’s a chance to build something better this time.',
            'If you believe it will work out, you’ll see opportunities. If you believe it won’t, you will see obstacles. – Wayne Dyer',
            'The only limits in our life are those we impose on ourselves. – Bob Proctor',
            'You can’t cross the sea merely by standing and staring at the water. – Rabindranath Tagore',
            'Success is not measured by money or power, but by the positive difference you make in people’s lives.',
            'The best preparation for tomorrow is doing your best today. – H. Jackson Brown Jr.',
            'Don’t let what you cannot do interfere with what you can do. – John Wooden',
            'You are your only limit.',
            'The struggle you’re in today is developing the strength you need for tomorrow.',
            'Don’t be discouraged. It’s often the last key in the bunch that opens the lock.',
            'You have within you right now, everything you need to deal with whatever the world can throw at you. – Brian Tracy',
            'The only way to do great work is to love what you do. – Steve Jobs',
            'Push yourself, because no one else is going to do it for you.'
        ];

        foreach ($quotes as $quote) {
            Quote::create(['quote' => $quote]);
        }
    }
}
